"use client";

import { useState } from "react";
import { toast } from "sonner";
import { Sparkles, ShieldAlert, CalendarDays } from "lucide-react";
import { apiFetch, HttpError } from "@/lib/api-client";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import type { InsightDTO } from "@/types";

const severityStyles: Record<string, string> = {
  info: "border-border",
  warning: "border-warning/60 bg-warning/5",
  critical: "border-critical/60 bg-critical/5",
};

const KINDS = [
  { kind: "summary", label: "Suggestions", icon: Sparkles },
  { kind: "burnout", label: "Burnout check", icon: ShieldAlert },
  { kind: "weekly", label: "Weekly", icon: CalendarDays },
] as const;

export function InsightsPanel() {
  const [insight, setInsight] = useState<InsightDTO | null>(null);
  const [loading, setLoading] = useState<string | null>(null);

  async function generate(kind: string) {
    setLoading(kind);
    try {
      const r = await apiFetch<{ data: InsightDTO }>("/api/insights", {
        method: "POST",
        body: JSON.stringify({ kind }),
        timeoutMs: 30_000,
      });
      setInsight(r.data);
    } catch (e) {
      if (e instanceof HttpError && e.status === 429) {
        toast.error("Slow down a moment — try again shortly.");
      } else {
        toast.error("Couldn't generate an insight. Please try again.");
      }
    } finally {
      setLoading(null);
    }
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Sparkles className="size-4 text-primary" aria-hidden />
          AI wellness insights
        </CardTitle>
        <CardDescription>
          Personalized, non-clinical guidance from your recent data.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="flex flex-wrap gap-2">
          {KINDS.map((k) => (
            <Button
              key={k.kind}
              size="sm"
              variant="outline"
              disabled={loading !== null}
              onClick={() => generate(k.kind)}
            >
              <k.icon className="size-4" aria-hidden />
              {loading === k.kind ? "Thinking…" : k.label}
            </Button>
          ))}
        </div>

        {insight ? (
          <div
            className={cn(
              "rounded-[--radius-md] border p-4",
              severityStyles[insight.severity] ?? severityStyles.info,
            )}
            aria-live="polite"
          >
            <p className="font-medium">{insight.title}</p>
            <p className="mt-1 whitespace-pre-line text-sm text-muted-foreground">
              {insight.body}
            </p>
            <p className="mt-2 text-[11px] text-muted-foreground">
              {insight.model ? `Generated by ${insight.model}` : "Offline guidance"}
            </p>
          </div>
        ) : (
          <p className="rounded-[--radius-md] bg-muted p-4 text-sm text-muted-foreground">
            Tap a button above to generate guidance. Works even if AI is
            unavailable — you&apos;ll always get safe, practical support.
          </p>
        )}
      </CardContent>
    </Card>
  );
}
